const portfolio = [
  {
    projectName: "Rent Right",
    projectType: "Real Estate website",
    stack: "Front-End",
    href: "https://rr-web-three.vercel.app",
    images: [
      "/png/rr/1.png",
      "/png/rr/2.png",
      "/png/rr/3.png",
      "/png/rr/4.png",
      "/png/rr/5.png",
      "/png/rr/6.png",
    ],
  },
  {
    projectName: "GetLinked",
    projectType: "getLinked website",
    stack: "Front-End",
    href: "https://linked-blue.vercel.app",
    images: [
      "/png/getLinked/1.png",
      "/png/getLinked/2.png",
      "/png/getLinked/3.png",
      "/png/getLinked/4.png",
    ],
  },
  {
    projectName: "Clickbuy",
    projectType: "E-commerce website",
    stack: "Full-stack",
    href: "https://clickbuy.vercel.app",
    images: [
      "/png/clickbuy/1a.png",
      "/png/clickbuy/1b.png",
      "/png/clickbuy/2a.png",
      "/png/clickbuy/2b.png",
      "/png/clickbuy/3a.png",
      "/png/clickbuy/3b.png",
      "/png/clickbuy/4a.png",
      "/png/clickbuy/4b.png",
      "/png/clickbuy/5.png",
      "/png/clickbuy/6a.png",
      "/png/clickbuy/6b.png",
    ],
  },
  {
    projectName: "Wheatear Capital",
    projectType: "Business website",
    stack: "Full-stack",
    href: "https://wheatear-capital.vercel.app",
    images: [
      "/png/wheatear-capital/1.png",
      "/png/wheatear-capital/2.png",
      "/png/wheatear-capital/3.png",
      "/png/wheatear-capital/4.png",
      "/png/wheatear-capital/5.png",
    ],
  },
  {
    projectName: "Intrepid Housing Solutions",
    projectType: "Real Estate website",
    stack: "Front-End",
    href: "https://intrepid-housing-solutions-demo.vercel.app",
    images: [
      "/png/intrepid/1.png",
      "/png/intrepid/2.png",
      "/png/intrepid/3.png",
      "/png/intrepid/4.png",
      "/png/intrepid/5.png",
      "/png/intrepid/6.png",
    ],
  },
  {
    projectName: "Victorious Living Church",
    projectType: "Management website",
    stack: "Full-stack",
    href: "https://vlchurch-international.onrender.com",
    images: [
      "/png/vlc-international/1.png",
      "/png/vlc-international/2.png",
      "/png/vlc-international/3.png",
    ],
  },
];

export default portfolio;
